######################################################################
#
#         Powered by TabooLib 6.0
#
#  ___________      _________ .__            __
#  \__    __________\_   ___ \|  |__ _____ _/  |_
#  |    |  \_  __ /    \  \/|  |  \\__  \\   __\
#  |    |   |  | \\     \___|   Y  \/ __ \|  |
#  |____|   |__|   \______  |___|  (____  |__|
#  \/     \/     \/  TrChat 1.8
#                                ------ Author by Arasple, Maintainer by ItsFlicker
#
######################################################################

# General options
GENERAL:
  CHECK-UPDATE: true
  DEBUG: false
  DISABLED-WORLDS: [PUT_YOUR_WORLD_NAME_HERE, ANOTHER_WORLD]
  LOG-NORMAL: '[{0}] {1}: {2}'
  LOG-PRIVATE: '[{0}] {1} -> {2}: {3}'
  DEPEND-EXPANSIONS:
    - 'player'
    - 'server'
    - 'vault'
  PREVENT-TAB-COMPLETE: false
  # NONE, BUNGEE, VELOCITY
  PROXY: NONE

# Chat Color
# Perm Node: trchat.color.<CODE>
# HEX Color require trchat.color.*
#
# Enable options
CHAT-COLOR:
  CHAT: true
  SIGN: true
  ANVIL: true
  BOOK: true

# Chat Control
CHAT-CONTROL:
  # Anti similar text repeat (Maximum similarity 0-1)
  ANTI-REPEAT: 0.85
  # Chat cooldown
  COOLDOWN: 2.0
  # Chat text length limit
  LENGTH-LIMIT: 100