Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault']

Database:
  Method: LOCAL
  Local:
    File: '{data_folder}/data.db'
  Sqlite:
    host: localhost
    port: 3306
    user: root
    password: root
    database: root
    table: trchat
  Mongodb:
    Client: 'mongodb://localhost:3307'
    Database: trixey
    Collection: chat

Chat:
  Anti-Repeat: 0.85
  Cooldown: 2.0
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'