name: Error Report
description: 'Warning: Failure to properly follow the prompts for feedback errors will be closed.'
title: "[issue] "
labels: ['Bug | 漏洞']
body:
  - type: checkboxes
    id: latests
    attributes:
      label: 'Whether the latest version has been tried'
      description: 'Your problem may have been found and fixed in the [latest version](https://github.com/TrPlugins/TrChat/actions)'
      options:
        - label: 'I have updated TrChat to the latest version, and the issue is also reproduced.'
          required: true

  - type: checkboxes
    id: wikis
    attributes:
      label: 'Have you checked the Wiki'
      description: 'Often many problems are caused by not checking the wiki in detail, or the wiki already has a solution, have you read [Wiki](https://trchat.trixey.cc/guide/known-issues)?'
      options:
        - label: 'I have checked the Wiki for this problem and determined that the problem exists.'
          required: true

  - type: textarea
    id: description
    attributes:
      label: 'Detailed description'
      description: 'Actions and prerequisites that can be reproduced'
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: 'configuration file'
      description: 'The channel file or settings.yml where the error occurred'
      render: 'YAML'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 'logs'
      description: 'If there is a message/error in the server/client backend when an error occurs, please provide it'
    validations:
      required: false

  - type: textarea
    id: environments
    attributes:
      label: 'Server environment'
      description: 'Paste the results of /version and /plugins here'
      value: |
        Server version:
        ...
        Plugin list:
        ...
    validations:
      required: true
